### ISSUE TITLE
Investigate how to run Skulpt locally

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1309]
## Task Description
In order to know how to implement Skulpt and have it run locally, we need to investigate the following things:

- How to load Python files asynchronously as well as pre-load external libraries
- How to run code through Skulpt
- How to collect the code logs and combine them with the game logs
- Where to put this code in the project

We'll also need to investigate what to do in the following edge cases:

- If a student writes an infinite loop
- If a student stores global variables
- If a student uses multiple functions
- If a student wants to import a module

It would also be good to investigate how to make Skulpt run as a web worker.

**Comment by mrniket** [comment]
I've looked into this and may have come to the conclusion that Pyodide might be a better fit for us, here is my quick analysis:

## Skulpt

- Converts python to javascript which can then run on the browser
  - there could be bugs in the conversion
  - the conversion is not feature complete with Python features
- Designed for learning Python in the browser, but can have other use cases
- Only has partial support for Python 3
- Documentation hard to navigate, had to look into the code a lot to find out about APIs

### Figured out
- found out how to load files into Skulpt, you have to implement it yourself
- able to run avatar code within Skulpt using "Sk.importMainWithBody"
- You can pass in a function to collect output from Skulpt
- timing out code that takes more than x milliseconds to run
- multiple functions, nothing special needed to be done

### Haven't figured out:
- global variables or a suitable workaround due to the way SKulpt requires you to run code
- importing modules, I assume this is possible however not all python modules may be convert into Skulpt js.

## Pyodide

- Python runtime compiled to Web assembly
  - for our usage, full access to Python APIs (I think `import os` won't work)
  - fast
  - Entire runtime in the browser means large download size: ~5-10mb, although this would be cached 
- Designed for bringing the scientific data stack into the browser, but can be used anywhere you want Python to run in the browser
- Currently in alpha
- Backed by Mozilla

### Figured out
- Loading other python files/modules, just used `micropip` to install third-party packages. We can expose our worker api files in a python package and then load it in to the frontend
- Run avatars code, once we have loaded in the worker API package run `pyodide.runPython`
- Documentation for running code in a worker
- global variables
- multiple functions, nothing special needed to be done
- since it's just the Python runtime, there is less API to worry about or learn
- importing modules/packages. There is a virtual filesystem inside the Pyodide Python runtime.

### Not figured out 
- How to stop Pyodide running if the user code takes too long (e.g. in the example of a `while True:` loop)

That's how far I got so far. This link may also prove useful: https://anvil.works/blog/python-in-the-browser-talk

**Comment by faucomte97** [comment]
I think this makes sense and is really clear :) And yeah it sounds like Pyodide is a better fit - slightly concerned that it is only in alpha for now but since it has a bigger following and better documentation I think we can go for it :)

**Comment by mrniket** [comment]
Thanks! 😊 Closing this issue now, we will modify the other tasks in the epic when we get to them
