### ISSUE TITLE
Improve thread safety of turn manager / worker manager / game state.

### ISSUE THREAD

**Issue by PhydeauxLeChien** [ocadotechnology/aimmo#140]
Currently, both `TurnManager` and `WorkerManager` each activate a different lock (stored in their respective data objects) before making alterations to the same `GameState` object. This may have strange effects, e.g. a race condition when an avatar is added while a turn is being processed.

~~In addition, both of the above locks seem to provide little-to-no thread safety for any other purpose, since as far as I can see they are each activated by only one thread.~~

Proposal:
- Add a single lock to the `GameState` class itself.
- Have each method assert that the lock is activated.
- Remove the separate locks in `TurnManager` and `WorkerManager`

**Comment by joshuablake** [comment]
The current WorkerManager locks do have a purpose as the workers are created in parallel.

**Comment by joshuablake** [comment]
Proposed solution:

1. Move responsibility for adding/removing/re-spawning avatars to its own method/class (rather than it being in `AttackAction` and `WorkerManager`). This also solves #138.
2. `WorkerManager` does not touch any state except attributes of `WorkerManagerData`.
3. During the `TurnManager.run_turn` method (and anything it calls), `TurnManager` only reads `GameState`.
4. After all actions are completed, `TurnManager` updates `GameState`.
5. Then perform the additon/removal.

Since `GameState` (which should be the only global state) is only modified in 4 and 5, which are both single-threaded, then the entire game should be thread-safe without locks (may be required in `WorkerManagerData`, although might be able to implement using atomic operations on built-ins which is thread-safe).

Here, the only concurrency is in:

* Creating aimmo-game-worker instances in `WorkerManager.spawn`.
* Fetching avatar's actions in `SequentialTurnManager.run_turn`.

Off-topic for this issue but relevant for implementation: currently `WorkerManager` uses green threads (from `eventlet`) and `SequentialTurnManager` uses real threads (from `threading`). Do we want to keep this or is it better to agree on a thread model?
