### ISSUE TITLE
Can't access aimmo locally anymore

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/aimmo#192]
If you access aimmo locally (http://127.0.0.1:8000/players)
you get a "TypeError at /players/".
int() argument must be a string or a number, not 'SimpleLazyObject'
In template aimmo/players/templates/players/base.html, error at line 42

(Might explain the error 500 when trying to access aimmo on staging!)

**Comment by Spycho** [comment]
I think its related to the removal of staff_required, as we then don't enforce we have a logged in user, which that page is actually relying on (debatably incorrectly).

The template tag `game_dropdown_list` in the base template calls `Game.objects.for_user(context.request.user)` which goes awry if you don't have a "real" user.

Similar SO issue: http://stackoverflow.com/questions/15878860/int-argument-must-be-a-string-or-a-number-not-simplelazyobject

We probably need to think about which pages we actually want to force you to be logged in to see. E.g. there's probably no harm in letting people watch public games without being logged in, however the user wont have an Avatar, so the JS that expects it to have one so it can draw a square on the user's Avatar would need to be made more complex to deal with the no-user case, which arguably we wouldn't want to do...

For now, I'll "fix" the template tag to function without a user (just showing public games). However, we might run into further issues if other things rely on being logged in, (e.g. the watch JS).

Of note, this obviously shouldn't be problem if you are logged in (though I can't test it because you can't log in, because the base template breaks if not logged in so the login page doesn't work), so I don't think it explains the 500 on staging.

Also, it didn't occur during local testing before pushing to master because I happened to be logged in. We probably need better tests around here. Hitting the views may have been sufficient to uncover the issue?
