### ISSUE TITLE
Imports in root on travis don't work but locally they do

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo#235]
Clearly an issue with sys.path here as found in today's Code For Life session. Something that needs to be looked at if we want to make use of generic methods etc.

**Comment by danalex97** [comment]
@OlafSzmidt  @ramonfmir Do we have some stack traces for this?

**Comment by OlafSzmidt** [comment]
Unfortunately not, but lately we found another issue with imports from the `Cell` class. They could not be resolved by the tests. When we moved them into a separate package, they worked.

Cyclic referencing?

**Comment by danalex97** [comment]
By root you mean the `aimmo` folder, right? I think we are not supposed to be able to import "inner" packages from `aimmo-game`, `aimmo-game-creator`, etc. as they are each independent services, each running in their own container/on their own port. Note we don't have an `__init__.py` in the root.

Tough, I see the point as we might want to use generic methods, as you said.

**Comment by OlafSzmidt** [comment]
In root of the package. I can't remember exactly what this issue was about. We should have saved the stack traces.

But I don't think the architecture is great in that sense, because the `worker` contains identical code to the `aimmo-game`.

**Comment by danalex97** [comment]
I think the intention was keeping each service with its own container. This is also done like this for security while running the user code. I don't know what are the best patterns we can use in this case.

The problem is how can we add the shared code to the containers without actually adding the whole code. (i.e. the user should not be able to access the `aimmo-game` code)

**Comment by OlafSzmidt** [comment]
Seems fixed.
