### ISSUE TITLE
Add actions to cheat sheet

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#535]
Wait action (inc pickup)
Move action (inc directions)
Attack action

**Comment by j4mesholland** [comment]
**Pickups:**

- HealthPickup 
- InvulnerabilityPickup
- DamageBoostPickup

**Comment by j4mesholland** [comment]
1st draft, please comment:

![Actions for cheat sheet.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/88be281a-672f-488e-b777-b71d83192f4e)

**Comment by mariaFernando** [comment]
A few things:
1. Since it's phrased "ability to Move the avatar" before, maybe we shouldn't have the word "move" again on "move north", etc?
2. The second section isn't very clear - these aren't actions and the explanation should probably be rephrased ("program your avatar" doesn't really describe the object listed, and seek, pick up, give resilience, repair aren't attributes of the objects listed)

**Comment by j4mesholland** [comment]
2nd draft. I have separated the actions and pickups into their own sections:

![Screen Shot 2018-04-25 at 13.22.19.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/c7617d99-269d-4e63-8360-bb7edfe1ad4c)


![Screen Shot 2018-04-25 at 13.22.28.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/2c3a3d67-d734-4b0a-8067-e3beb1f5e6dd)

**Comment by CelineBoudier** [comment]
Some comments:
- MoveAction(direction.ALL_DIRECTIONS) doesn't really make sense because you still have to pick a direction. That's why we pick a direction at random from the direction.ALL_DIRECTIONS list in the example code on the website
- AttackAction also takes a direction in parameter (the direction of the other player you want to attack)
- WaitAction should be written WaitAction() to be consistent
- The descriptions of what the Action does are not consistent (Capital letters or not)
- Say that you collect pickups by walking on the cell??
- The main description should be consistent in terms of naming: Health, Invulnerability and BoostDamage
- Capital letter at the start of pickups available please
Thank you :)

**Comment by mariaFernando** [comment]
Still think the explanations should be more consistent...

_**These Actions return:** 
The ability to Move the avatar: (...)
Program your avatar(...) ---_ in here it should be something like "The ability to Attack" 
_Your avatar waits (...)_ --- in here it should be something like "The ability to Wait"
etc.

Also, maybe instead of saying "return", maybe just "allow"? Actions returning "abilities" sounds weird imo

On the pickups part, they also don't return anything, they're objects on their own so wouldn't return "seek and pick up health", etc. I'd just say "These pickups are: health, resilience, damage"? Kids should be familiar with these (also, damage boost doesn't repair the avatar from damage, does it?)

**Comment by j4mesholland** [comment]
What does Damage boost do?

**Comment by CelineBoudier** [comment]
I agree with @mariaFernando returns is a specific keyword in Python. For instance the handle_turn functions returns an Action.
Here it's more like a description of said Actions.

DamageBoost icnreases the attacke strength of the Avatar, so they would produce more damage when performing an AttackAction()

**Comment by j4mesholland** [comment]
Updated PDF here: 

[https://app.zenhub.com/files/39072690/0bc23bc2-52eb-409b-8295-485e136ffe35/download](https://app.zenhub.com/files/39072690/0bc23bc2-52eb-409b-8295-485e136ffe35/download)

**Comment by j4mesholland** [comment]
[https://app.zenhub.com/files/39072690/9c58f51d-0ce7-4ea2-a956-34ed98acf49e/download](https://app.zenhub.com/files/39072690/9c58f51d-0ce7-4ea2-a956-34ed98acf49e/download)

I've made those changes. Please review

**Comment by mariaFernando** [comment]
Yep, what @CelineBoudier said :)

**Comment by CelineBoudier** [comment]
:+1:
