### ISSUE TITLE
Kubernetes scalability sanity check

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#570]
- Figure out how to check scalability
- Write a test to check either manually or auto
- Monitor the cluster
- Fix or workaround any issues that may arise

**Comment by OlafSzmidt** [comment]
Definitely a scalability issue there. On staging we were only able to run 11 games before new pods were unschedulable. 

The issue is most likely in our requests for games. We require a tenth of the CPU for each game to be reserved. New games can't spawn by the RC later. Our node pool is 3 nodes with 1vCPU each. That's 30 games tops (not including workers, RC's and other things like nginx).

Taking this on branches `test_kubernetes_scaling` on appengine and `dbclear_cpulimits` on aimmo. Deploying dev to test new resource limitations tomorrow morning.

**Comment by OlafSzmidt** [comment]
All changes have been made, but waiting for beta account users to be implemented before we can test on a large scale. Right now this overloads our database when we do this through the administration panel of django (because each game has 140k `can_play` links to all the users in the database). 

Stalled for now ;)
