### ISSUE TITLE
Warning about missing logging handlers

### ISSUE THREAD

**Issue by jishi9** [ocadotechnology/aimmo#61]
The following warning is emitted by `example_project/manage.py` (which is executed by `./run`):
```
No handlers could be found for logger "django_autoconfig.environment_settings.autoconfig"
```

Once this is fixed, a logged error message is revealed:
```
WARNING:django_autoconfig.environment_settings.autoconfig:Unable to parse setting SETTINGS_MODULE=example_project.settings (malformed string)
```

**Comment by jishi9** [comment]
Is `example_project.settings` intended to be a quoted string, i.e. `"example_project.settings"` ?

This is used in `example_project/manage.py` and `example_project/example_project/manage.py`:
```
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "example_project.settings")
```

**Comment by mikebryant** [comment]
`DJANGO_SETTINGS_MODULE` is supposed to be set to `example_project.settings`
It's a special case, one that's just being ignored by the environment parsing code, and currently generates a spurious warning.

If it's bugging you, raise an issue in https://github.com/mikebryant/django-autoconfig, I wouldn't object to a pull request to disable the warning for this particular setting.



The logging warning is a consequence of the order we have to set up the project. Django logging is supposed to be configured by the settings file, but in order to automatically configure it, we're running code prior to this happening.
Setting up a `logging.basicConfig()` in `example_project/manage.py` shouldn't break anything.. I think the Django setup for logging will then overwrite it shortly afterwards.

**Comment by jishi9** [comment]
> If it's bugging you, raise an issue in https://github.com/mikebryant/django-autoconfig, I wouldn't object to a pull request to disable the warning for this particular setting.

Done: https://github.com/mikebryant/django-autoconfig/pull/31
