### ISSUE TITLE
Possible code resilience improvements (?)

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo#654]
- When we call `handle_turn()` and then try to return the action, we could have checks that the action is actually an action and not any arbitrary code. Right now a possible security vulnerability is that a user implements a class, returns the callback and the `serialise()` method executes something malicious when we call it on our server. There will be a fail later on in the code, but straight away we call serialise() on the code.
- Have static checks before actually checking for runtime errors.

Open for further discussion :)

**Comment by NiallEgan** [comment]
I'm not sure there is really an issue here. The user can execute arbitrary code on a worker pod, but this is isolated from everything else so shouldn't cause a problem. The user can't gain control of the game pod because if the user returns code that is not a 'valid action', then the dict lookup in `_construct_action` will fail (this exception is later caught). 

However I agree that this is something we should always be guarding against, especially when we start to think about how we want to return errors from the worker pod.
