### ISSUE TITLE
AI:MMO user guide update

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/aimmo#881]
## Task Description

Update current user guide as per Rebecca's recommendation (on google drive)

## Acceptance Criteria

- [ ] Rebecca approves the new guide

## Analytics Requirements

**Comment by faucomte97** [comment]
Not stale

**Comment by j4mesholland** [comment]
I have updated this as per Rebecca's comments. This will document will be continually updated as we make changes to the game.

It is up to date as of 29 January 2019.

@rdcruzCFL please can you review. Updated PDF for approval here:

[https://app.zenhub.com/files/39072690/b7159432-df8f-4306-b944-da9182a7b3cb/download](https://app.zenhub.com/files/39072690/b7159432-df8f-4306-b944-da9182a7b3cb/download)

**Comment by rdcruzCFL** [comment]
- Can we reword this paragraph a bit?
*A prior knowledge in coding concepts is required in order to play this game.This knowledge can be acquired by playing our Rapid Router game.*
This isn't really accurate. It can help but they will need to have a good grasp of the concepts listed (somewhere, I can find them), before they can reasonably use AI:MMO
Perhaps we could say something like:
*Pupils should have prior experience of using variables, selection and iteration in Python. Some understanding of defining and calling sub-programs is also helpful.*

- Can we also avoid the use of the term, coding? Programming is more accurate. Coding is just writing the code, not planning it etc.

- Second page, Code view column
*After several seconds, a notification will appear in the map view to show that their avatar is now running the updated code.*
Replace with *After a few seconds*? It sounds shorter. It doesn't take long, does it?

- The console log will display *the output of* any print statement output as well as error messages

- Instead of *Players can use the console log to display print statements, so that they can test their
code is working correctly.*, perhaps, *Players can add print statements to help them debug their code.*

- Map view column: Has the blue pointer been changed now? (para 1)

**Comment by j4mesholland** [comment]
I have made those changes. The blue pointer hasn't been changed and is active on the latest version so that para is correct.

@rdcruzCFL can you please give this a final check over, thanks.

[https://app.zenhub.com/files/39072690/0e8c8a00-8243-4761-b789-135fd4748f51/download](https://app.zenhub.com/files/39072690/0e8c8a00-8243-4761-b789-135fd4748f51/download)
