### ISSUE TITLE
Game UI code hints design

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#905]
## Task Description
Try out various formats for showing code methods:
- Drawers / sheets
- Cards

## Acceptance Criteria
- [ ] Show the different options to the team before creating prototypes

## Analytics Requirements

**Comment by j4mesholland** [comment]
Please review the prototype: https://sketch.cloud/s/Px84v/agDzgZZ/play

**Comment by faucomte97** [comment]
This looks really good! We really like the whole look of it, and the top and side bars are really useful :)
A couple of ideas / suggestions:

- Will the Move Actions be alongside other code examples in the 'Code Methods' drawer? We were wondering because if not, it might be an idea to simply call it 'Move Actions' altogether.

- The Challenge goal drawer is great! Having a clear tutorial for the first goal is really nice :) Paris suggests maybe having the left / right arrows (and the page counter) in place of the minimise and close icons. We think that maybe the minimise and close icons are superfluous - since the user can already close the challenge goal drawer by clicking the fop. As for minimising, we thought it might be easier for the user if they just had to click on the darker pink bar the top to minimise and expand.
Once it's minimised, it might be nicer to have the Challenge Goal bar less wide?

- Also just a written reminder that we'll want to move the compass to the top left of the map screen :)

**Comment by j4mesholland** [comment]
Thank you. 

- I will add the minimised goal as a default when the sidebar is activated
- The minimised goal bar does not need to be full width
- The Code methods are contextual to the challenge

**Comment by CelineBoudier** [comment]
looks nice James

**Comment by rdcruzCFL** [comment]
That looks really good, James! :-)
- I like the avatar label, it is very clear.
- The top bar is very useful. I assume that icons will have tool tips on them?
- The sidebar is great, really neat, clear and very useful. I assume that you can tuck it away again? That only seemed to work sometimes on your demo.
- The contrast on the (shown) code is better too. 
- Does one of those icons centre the map on your avatar?
