### ISSUE TITLE
Optimise kubernetes pods

### ISSUE THREAD

**Issue by dent50cent** [ocadotechnology/aimmo#929]
## Task Description
Currently, it seems our servers cannot handle more than ~35 games & ~235 workers after you take into account the resources needed for the game creator and ingress etc. However, the pods themselves utilize very little of the resources they are allocated. So it should be possible to decrease the pod limits to squeeze more out of our servers (Also gives more room to add things like Prometheus monitoring.

## Acceptance Criteria
- [ ] Identify how much of a givens pods resources are being used (upper limit)
- [ ] change the pod limits to match what was found.

**Comment by OlafSzmidt** [comment]
@dent50cent A lot has changed since so might not be useful anymore. But we've done this before. There's a few things to consider. It might be more useful to scale sideways on GCE rather than having more powerful vCPUs. Lots of resources are eaten up by k8s background stuff running too. Statistical modules etc. We did some testing using kubesec and found this to be better for the first beta users:

https://github.com/ocadotechnology/aimmo/pull/583
https://github.com/ocadotechnology/aimmo/issues/570

**Comment by dent50cent** [comment]
Made obsolete by #983
